#!/bin/bash

# 纪念网站 GitHub 设置脚本
# 此脚本帮助您将纪念网站上传到 GitHub

echo "=== 纪念网站 GitHub 设置 ==="
echo ""
echo "您的纪念网站文件已准备就绪！"
echo "位置: $(pwd)"
echo ""
echo "已创建的文件："
echo "- index.html (主网站文件)"
echo "- styles.css (美丽样式)"
echo "- script.js (交互功能)"
echo "- README.md (说明文档)"
echo "- images/ (照片文件夹)"
echo ""
echo "=== 下一步 ==="
echo ""
echo "1. 安装 GIT（如果尚未安装）："
echo "   - 访问: https://git-scm.com/download/mac"
echo "   - 下载并安装 macOS 版 Git"
echo "   - 或通过 Homebrew 安装: brew install git"
echo ""
echo "2. 自定义您的网站："
echo "   - 编辑 index.html 添加您母亲的姓名和日期"
echo "   - 将照片添加到 images/ 文件夹"
echo "   - 更新生平简介、美好回忆、人生历程和缅怀留言部分的内容"
echo ""
echo "3. 创建 GITHUB 仓库："
echo "   - 访问 https://github.com"
echo "   - 点击 'New repository'"
echo "   - 命名为类似 'memorial-website' 的名称"
echo "   - 设为公开（免费托管需要）"
echo "   - 不要用 README 初始化（我们已经有了）"
echo ""
echo "4. 上传到 GITHUB："
echo "   安装 Git 后，运行以下命令："
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit - Memorial website'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/您的用户名/您的仓库名.git"
echo "   git push -u origin main"
echo ""
echo "5. 启用 GITHUB PAGES："
echo "   - 进入仓库设置"
echo "   - 滚动到 'Pages' 部分"
echo "   - 选择 'Deploy from a branch'"
echo "   - 选择 'main' 分支和 '/ (root)' 文件夹"
echo "   - 点击 'Save'"
echo ""
echo "6. 访问您的网站："
echo "   您的网站将在以下地址可用："
echo "   https://您的用户名.github.io/您的仓库名"
echo ""
echo "=== 重要提示 ==="
echo "- 将您的用户名和您的仓库名替换为实际的 GitHub 用户名和仓库名称"
echo "- GitHub Pages 部署您的网站可能需要几分钟"
echo "- 上传前确保将照片添加到 images/ 文件夹"
echo "- 通过在网页浏览器中打开 index.html 来本地测试您的网站"
echo ""
echo "需要帮助？查看 README.md 文件获取详细说明！"
echo ""
echo "愿此网站成为您母亲记忆的美丽纪念。❤️"